version: '3.9'

services:

  jenkins:
    image: jenkins-custom
    restart: always
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ci-cd

  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    volumes:
     - nexus-data:/nexus-data
    networks:
      - ci-cd

  sonarqube:
    image: sonar-custom
    depends_on:
      - sonarqube-db
    ports:
      - "9000:9000"
    volumes:
      - sonarqube-data:/opt/sonarqube/data
    user: "1000:1000"
    environment:
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=sonarqube
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-db:5432/sonarqube
    networks:
      - ci-cd

  sonarqube-db:
    image: postgres:12
    environment:
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarqube
      - POSTGRES_DB=sonarqube
    volumes:
      - sonarqube-db-data:/var/lib/postgresql/data
    networks:
      - ci-cd
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - sonarqube-db
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - ci-cd

networks:
  ci-cd:

volumes:
  jenkins-data:
  nexus-data:
  sonarqube-data:
  sonarqube-db-data:
  pgadmin-data: