version: '3.9'

services:

  jenkins:
    build: 
      context: ./jenkins
      dockerfile: Dockerfile
    #image: jenkins-custom
    restart: always
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ci-cd

  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    volumes:
     - nexus-data:/nexus-data
    networks:
      - ci-cd

  sonarqube:
    build: 
      context: ./sonar
      dockerfile: Dockerfile
    #image: sonar-custom
    depends_on:
      - sonarqube-db
    ports:
      - "9000:9000"
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-logs:/opt/sonarqube/logs
      - sonarqube-extensions:/opt/sonarqube/extensions
    user: "1000:1000"
    environment:
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=sonarqube
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-db:5432/sonarqube
    networks:
      - ci-cd

  sonarqube-db:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=sonarqube
    volumes:
      - sonarqube-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ci-cd
      - db 
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
    depends_on:
      - sonarqube-db
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - db

networks:
  ci-cd:
  db:

volumes:
  jenkins-data:
  nexus-data:
  sonarqube-data:
  sonarqube-logs:
  sonarqube-extensions:
  sonarqube-db-data:
  pgadmin-data: