version: '3.9'

services:

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      - ci-cd

  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
    networks:
      - ci-cd

  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube-data:/opt/sonarqube/data
    networks:
      - ci-cd

  sonarqube-db:
    image: postgres:12
    environment:
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarqube
      - POSTGRES_DB=sonarqube
    volumes:
      - sonarqube-db-data:/var/lib/postgresql/data
    networks:
      - ci-cd
  
  httpd:
  image: httpd:2.4
  ports:
    - "80:80"
  volumes:
    - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
    - ./html:/usr/local/apache2/htdocs/
  networks:
    - ci-cd

networks:
  ci-cd:

volumes:
  jenkins-data:
  nexus-data:
  sonarqube-data:
  sonarqube-db-data: